title: Orchid - Easy Server Management
logo: /assets/img/orchid.png
description: Orchid is a bash script aimed to make life easier for geeks & sysadmins.
show_downloads: true
google_analytics: UA-162785731-2
theme: jekyll-theme-minimal
